/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IStableCreditInterface extends ethers.utils.Interface {
  functions: {
    "access()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "convertCreditToFeeToken(uint256)": FunctionFragment;
    "feeToken()": FunctionFragment;
    "networkDebt()": FunctionFragment;
    "reservePool()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "access", values?: undefined): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "convertCreditToFeeToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "networkDebt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reservePool",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "access", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertCreditToFeeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "networkDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservePool",
    data: BytesLike
  ): Result;

  events: {
    "CreditBalanceRepayed(address,uint128)": EventFragment;
    "CreditDefault(address)": EventFragment;
    "CreditLimitExtended(address,uint256)": EventFragment;
    "CreditLineCreated(address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "MembersDemurraged(uint256)": EventFragment;
    "NetworkDebtBurned(address,uint256)": EventFragment;
    "PeriodEnded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreditBalanceRepayed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreditDefault"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreditLimitExtended"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreditLineCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MembersDemurraged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NetworkDebtBurned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PeriodEnded"): EventFragment;
}

export type CreditBalanceRepayedEvent = TypedEvent<
  [string, BigNumber] & { member: string; amount: BigNumber }
>;

export type CreditDefaultEvent = TypedEvent<[string] & { member: string }>;

export type CreditLimitExtendedEvent = TypedEvent<
  [string, BigNumber] & { member: string; creditLimit: BigNumber }
>;

export type CreditLineCreatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    member: string;
    creditLimit: BigNumber;
    pastDueTime: BigNumber;
    defaultTime: BigNumber;
    feePercent: BigNumber;
    balance: BigNumber;
  }
>;

export type MembersDemurragedEvent = TypedEvent<
  [BigNumber] & { amount: BigNumber }
>;

export type NetworkDebtBurnedEvent = TypedEvent<
  [string, BigNumber] & { member: string; amount: BigNumber }
>;

export type PeriodEndedEvent = TypedEvent<[string] & { member: string }>;

export class IStableCredit extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IStableCreditInterface;

  functions: {
    access(overrides?: CallOverrides): Promise<[string]>;

    balanceOf(_member: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    convertCreditToFeeToken(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    feeToken(overrides?: CallOverrides): Promise<[string]>;

    networkDebt(overrides?: CallOverrides): Promise<[BigNumber]>;

    reservePool(overrides?: CallOverrides): Promise<[string]>;
  };

  access(overrides?: CallOverrides): Promise<string>;

  balanceOf(_member: string, overrides?: CallOverrides): Promise<BigNumber>;

  convertCreditToFeeToken(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  feeToken(overrides?: CallOverrides): Promise<string>;

  networkDebt(overrides?: CallOverrides): Promise<BigNumber>;

  reservePool(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    access(overrides?: CallOverrides): Promise<string>;

    balanceOf(_member: string, overrides?: CallOverrides): Promise<BigNumber>;

    convertCreditToFeeToken(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeToken(overrides?: CallOverrides): Promise<string>;

    networkDebt(overrides?: CallOverrides): Promise<BigNumber>;

    reservePool(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CreditBalanceRepayed(address,uint128)"(
      member?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; amount: BigNumber }
    >;

    CreditBalanceRepayed(
      member?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; amount: BigNumber }
    >;

    "CreditDefault(address)"(
      member?: null
    ): TypedEventFilter<[string], { member: string }>;

    CreditDefault(
      member?: null
    ): TypedEventFilter<[string], { member: string }>;

    "CreditLimitExtended(address,uint256)"(
      member?: null,
      creditLimit?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; creditLimit: BigNumber }
    >;

    CreditLimitExtended(
      member?: null,
      creditLimit?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; creditLimit: BigNumber }
    >;

    "CreditLineCreated(address,uint256,uint256,uint256,uint256,uint256)"(
      member?: null,
      creditLimit?: null,
      pastDueTime?: null,
      defaultTime?: null,
      feePercent?: null,
      balance?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        member: string;
        creditLimit: BigNumber;
        pastDueTime: BigNumber;
        defaultTime: BigNumber;
        feePercent: BigNumber;
        balance: BigNumber;
      }
    >;

    CreditLineCreated(
      member?: null,
      creditLimit?: null,
      pastDueTime?: null,
      defaultTime?: null,
      feePercent?: null,
      balance?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        member: string;
        creditLimit: BigNumber;
        pastDueTime: BigNumber;
        defaultTime: BigNumber;
        feePercent: BigNumber;
        balance: BigNumber;
      }
    >;

    "MembersDemurraged(uint256)"(
      amount?: null
    ): TypedEventFilter<[BigNumber], { amount: BigNumber }>;

    MembersDemurraged(
      amount?: null
    ): TypedEventFilter<[BigNumber], { amount: BigNumber }>;

    "NetworkDebtBurned(address,uint256)"(
      member?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; amount: BigNumber }
    >;

    NetworkDebtBurned(
      member?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; amount: BigNumber }
    >;

    "PeriodEnded(address)"(
      member?: null
    ): TypedEventFilter<[string], { member: string }>;

    PeriodEnded(member?: null): TypedEventFilter<[string], { member: string }>;
  };

  estimateGas: {
    access(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(_member: string, overrides?: CallOverrides): Promise<BigNumber>;

    convertCreditToFeeToken(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeToken(overrides?: CallOverrides): Promise<BigNumber>;

    networkDebt(overrides?: CallOverrides): Promise<BigNumber>;

    reservePool(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    access(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      _member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertCreditToFeeToken(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    networkDebt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reservePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
